export {default as Footer} from "./footer"
export {default as Navbar} from "./navbar"
export {default as Hero} from "./hero"
export {default as Breadcrumns} from "./breadcrumbs"
export {default as Modal} from "./model"
